[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.24.4" 
  TZ = "UTC"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.147.7"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.147.7"

